version: "3"
services:

  redis:
    image: redis
    restart: always
    ports:
      - "6380:6379"

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: eval
      NODE_ENV: docker
    ports:
      - "5433:5432"

  migration:
    build: 
      context: ./auth
      dockerfile: Dockerfile.migrations
    command: npx sequelize-cli db:migrate
    environment:
      NODE_ENV: docker
    depends_on:
      - db
      - redis
    
  auth-service:
    build: ./auth
    depends_on:
      - db
      - redis
    ports:
      - "4000:4000"
    environment:
      NUMBER_OF_SALTS_ROUNDS: 10
      JWT_SECRET_KEY: secret-key
      REDIS_HOST: docker.for.mac.localhost
      NODE_ENV: docker